# Generated by Django 5.2 on 2025-04-14 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('avatar', models.ImageField(upload_to='drama/actors/', verbose_name='头像')),
                ('biography', models.TextField(verbose_name='简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '演员',
                'verbose_name_plural': '演员',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('cover', models.ImageField(upload_to='drama/covers/', verbose_name='封面')),
                ('description', models.TextField(verbose_name='简介')),
                ('director', models.CharField(max_length=50, verbose_name='导演')),
                ('release_date', models.DateField(verbose_name='上线日期')),
                ('total_episodes', models.IntegerField(verbose_name='总集数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('offline', '已下线')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '短剧',
                'verbose_name_plural': '短剧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DramaActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, verbose_name='角色名')),
                ('is_protagonist', models.BooleanField(default=False, verbose_name='是否主角')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drama.actor', verbose_name='演员')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drama.drama', verbose_name='短剧')),
            ],
            options={
                'verbose_name': '短剧演员',
                'verbose_name_plural': '短剧演员',
                'unique_together': {('drama', 'actor')},
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='dramas',
            field=models.ManyToManyField(related_name='actors', through='drama.DramaActor', to='drama.drama', verbose_name='参演短剧'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('episode_number', models.IntegerField(verbose_name='集数')),
                ('video_url', models.URLField(verbose_name='视频链接')),
                ('duration', models.IntegerField(help_text='单位：秒', verbose_name='时长')),
                ('thumbnail', models.ImageField(upload_to='drama/thumbnails/', verbose_name='缩略图')),
                ('views', models.IntegerField(default=0, verbose_name='播放量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='drama.drama', verbose_name='所属短剧')),
            ],
            options={
                'verbose_name': '剧集',
                'verbose_name_plural': '剧集',
                'ordering': ['episode_number'],
                'unique_together': {('drama', 'episode_number')},
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='用户ID')),
                ('interaction_type', models.CharField(choices=[('view', '观看'), ('like', '点赞'), ('comment', '评论'), ('share', '分享')], max_length=20, verbose_name='互动类型')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='drama.drama', verbose_name='短剧')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='drama.episode', verbose_name='剧集')),
            ],
            options={
                'verbose_name': '用户互动',
                'verbose_name_plural': '用户互动',
                'ordering': ['-created_at'],
            },
        ),
    ]
