# Generated by Django 5.2 on 2025-04-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='drama',
            name='categories',
            field=models.ManyToManyField(related_name='dramas', to='drama.category', verbose_name='类别'),
        ),
    ]
