# Generated by Django 5.2 on 2025-04-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0002_category_drama_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞次数'),
        ),
        migrations.AddField(
            model_name='drama',
            name='play_count',
            field=models.IntegerField(default=0, verbose_name='播放次数'),
        ),
        migrations.AddField(
            model_name='drama',
            name='share_count',
            field=models.IntegerField(default=0, verbose_name='转发次数'),
        ),
    ]
