# Generated by Django 5.2 on 2025-04-14 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0003_drama_like_count_drama_play_count_drama_share_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recommend_drama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drama.drama', unique=True),
        ),
    ]
