# Generated by Django 5.2 on 2025-04-14 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0004_category_recommend_drama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='recommend_drama',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drama.drama'),
        ),
    ]
