# Generated by Django 5.2 on 2025-04-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0005_alter_category_recommend_drama'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
    ]
