# Generated by Django 5.2 on 2025-04-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0006_drama_is_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recommend_drama',
        ),
    ]
