# Generated by Django 5.2 on 2025-04-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0007_remove_category_recommend_drama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='is_recommended',
        ),
    ]
