# Generated by Django 5.2 on 2025-04-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0008_remove_drama_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='recommendation_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='推荐顺序'),
        ),
    ]
